# Generated by Django 4.2.1 on 2023-09-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramentas',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
